create database mybatis;
use mybatis;
create table `USERS_T` (
	`ID` INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`NAME` VARCHAR(64),
	`AGE`  INT(11)
);
INSERT INTO `USERS_T`(`NAME`,`AGE`) VALUES ('JASON', 27);
INSERT INTO `USERS_T`(`NAME`,`AGE`) VALUES ('TONY', 27);

create table `ORDERS_T` (
	`ORDER_ID` INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`ORDER_NO` VARCHAR(64),
	`ORDER_PRICE` FLOAT
);
INSERT INTO `ORDERS_T`(`ORDER_NO`, `ORDER_PRICE`) VALUES('aaaa', 23);
INSERT INTO `ORDERS_T`(`ORDER_NO`, `ORDER_PRICE`) VALUES('bbbb', 33);
INSERT INTO `ORDERS_T`(`ORDER_NO`, `ORDER_PRICE`) VALUES('cccc', 22);
COMMIT;